one:
	javac -d ./classes src/*One*.java && javac -cp ./lib/junit-4.10.jar:./classes -d ./classes test/*One*.java && java -cp ./lib/junit-4.10.jar:./classes TestRunnerOne
two:
	javac -d ./classes src/*Two*.java && javac -cp ./lib/junit-4.10.jar:./classes -d ./classes test/*Two*.java && java -cp ./lib/junit-4.10.jar:./classes TestRunnerTwo
three:
	javac -d ./classes src/*Three*.java && javac -cp ./lib/junit-4.10.jar:./classes -d ./classes test/*Three*.java && java -cp ./lib/junit-4.10.jar:./classes TestRunnerThree